# SDLC Workflow Rules

- 文件操作限项目根目录内
- 日期格式: YYYY-MM-DD
- 迭代目录格式: docs/iterations/YYYY-MM-DD/<seq>-<slug>-<type>/
  - <seq>: 当天内递增的 3 位序号，例 `001`
  - <slug>: 需求名 kebab-case (≤30 字符)
  - <type>: feature | fix | refactor | docs | test | chore
- Commit: Conventional Commits (feat/fix/docs/refactor/test/chore)
- 通知统一走 OpenClaw CLI
- Review/Test 循环上限由 REVIEW_MAX_ROUNDS 控制（默认 1 轮）
- 超限通知人工 + 中止 Pipeline
- 禁止直推 main/master 分支
- 禁止通知/日志泄露敏感信息（密钥/Token/密码）
- Codex Gate 默认使用 `codex exec --full-auto`
- Codex CLI 不可用时必须中止，不能自动跳过 Gate
- 测试文件统一存放 tests/ 目录（unit/ + e2e/ + reports/）
- 新需求处理前必须参考 docs/iterations/ 历史上下文
- 若项目已存在业务代码或工程结构，则进入 existing project mode，必须先生成：
  - `.claude/PROJECT_BASELINE.md`
  - `.claude/EXISTING_STRUCTURE.md`
  - `.claude/TEST_BASELINE.md`
- existing project mode 下，未经 `design.md` 明确批准，不得调整既有技术架构或重排 workspace
- 全栈项目默认遵循 Better-T-Stack 风格 monorepo：
  - `apps/web`：Web 前端应用
  - `apps/server`：后端 API / BFF / Worker 入口
  - `apps/native`：移动端应用（如存在）
  - `apps/docs`：文档站点（如存在）
  - `packages/*`：共享代码、类型、配置、SDK、业务模块
- 业务代码禁止随意落在新的顶层目录中；默认不允许新增根目录级 `web/`、`server/`、`api/`、`frontend/`、`backend/`
- Web 前端实现默认落在 `apps/web/src/`
- 后端实现默认落在 `apps/server/src/`
- 共享包默认按 Better-T-Stack 条件创建：`packages/config` 总是存在；`packages/env`、`packages/api`、`packages/auth`、`packages/db`、`packages/infra`、`packages/ui` 按所选能力启用
- 跨端共享逻辑默认进入 `packages/*`，不要在 `apps/web` 和 `apps/server` 间复制
- 设计文档必须声明目录影响：新增目录、修改目录、为什么不能复用现有目录
- existing project 的设计文档必须引用 baseline，说明本次需求是沿用既有结构还是批准的结构调整
- 若必须偏离 Better-T-Stack 结构，需在 `design.md` 中给出明确理由，并经过 Gate 1 审查通过
- 单元测试必须写入 `tests/unit/`，并按 workspace 镜像落位，如 `tests/unit/web/...`、`tests/unit/server/...`、`tests/unit/packages/...`
- E2E 测试必须写入 `tests/e2e/`，并维护"需求 ID / 场景 ID / 文件路径"的唯一映射，不得重复覆盖同一需求路径
- `tasks.md` 是执行状态单据：任务实现完成后，必须将任务标题从 `[ ]` 回写为 `[x]`，并同步勾选真实完成的验收标准
- 每个任务必须声明 Track 字段（取值：`frontend` | `backend` | `shared` | `infra` | `test`），用于按角色组织阅读和分派
- Track 必须与目标文件路径自洽：`apps/web/*`/`apps/native/*`/`packages/ui/*` → frontend；`apps/server/*`/`packages/api/*`/`packages/db/*` → backend；`packages/{config,env,auth}/*` → shared；`db/migrations/*` 与根目录配置/CI 文件 → infra；`tests/*` → test
- 一个任务只能属于一个 Track；跨端需求（如同时改前端表单与后端 API）必须在拆任务阶段拆为多个任务，禁止一个任务跨 Track
- `tasks.md` 必须在"任务总览"之后提供"任务 Track 汇总（按角色视图）"表，覆盖所有任务 ID，且总数与 Phase 总览一致
- `test` Track 仅允许出现在 Phase 3；Phase 1/2 实现任务里随手写的单元测试不计为 test Track
- 进入 `/sdlc-doit` 或 `/sdlc-doit-mini` 的测试阶段前，必须先检测项目当前具备的验证能力，不能静默跳过测试决策
- `TEST_BOOTSTRAP_POLICY` 决定缺少测试基础设施时的行为；existing project 默认推荐 `report`
- OpenClaw / 远程场景默认不依赖交互式 ask，优先通过报告和 TG 通知输出缺口与后续动作
- 测试链路为 `Playwright 预检 + Playwright MCP + CDP 最终交互验收`
- 最终交互测试与最终测试报告以 Playwright MCP 和 CDP 产物为准
- **Artifact Gate（产物验证门禁）**：标记 test-pipeline 完成前，必须验证以下产物全部存在于磁盘：
  - `tests/reports/playwright/<slug>-*.md`（至少一份 Playwright MCP 验收记录）
  - `tests/reports/<slug>-acceptance-report.html`（最终验收报告 HTML）
  - 缺少任何一项 → 禁止标记 test-pipeline 为 completed
- **Todo 状态与磁盘产物交叉验证**：`manage_todo_list` 的 completed 状态必须与真实磁盘产物一致，不能只靠内存标记
- **Token 耗尽保护**：若 context_usage > 70%，必须先执行 /compact 再进入 test-pipeline（步骤 ⑨）
- **Pipeline 断点续跑**：status.json 新增 `pipeline_stage` 字段，token 耗尽时写入 `test-pipeline-incomplete`；新会话启动时读取此字段，从中断阶段继续执行而非跳过
- 架构文档 `.claude/ARCHITECTURE.md`、安全规范 `.claude/SECURITY.md`、编码规范 `.claude/CODING_GUIDELINES.md` 与 `CLAUDE.md` 一同位于 `.claude/` 目录
- `proposal` 命令完成后必须写入 `status.json`，标记 `phase: pending_review`
- `apply` 命令启动前必须检查 `status.json`，仅当 `phase == approved` 时允许执行
- `doit` 命令为全自动模式，内部执行 proposal + apply 不停顿
